const mongoose = require('mongoose');

const abaSchema = new mongoose.Schema({
    // Removed direct bookingId reference for now, as requested.
    // An external reference, which could eventually be a booking's reference code, but not a direct ObjectId link.
    external_reference: {
        type: String,
        required: false,
        unique: true, // Assuming external_reference will be unique per transaction
        sparse: true
    },
    // The unique transaction ID for the Payway transaction
    transaction_id: {
        type: String,
        required: true,
        unique: true,
        sparse: true,
    },
    qr_string: {
        type: String
    },
    qr_image: {
        type: String
    },
    amount: {
        type: Number,
        required: true,
    },
    currency: {
        type: String,
        enum: ['USD', 'KHR'],
        default: 'USD',
    },
    status: {
        type: String,
        enum: ['Pending', 'Completed', 'Failed'],
        default: 'Pending',
    },
    // The security hash generated by the backend and sent to ABA
    request_hash: {
        type: String,
        required: true,
    },
    // The full response from the ABA callback/webhook for logging and auditing
    callback_response: {
        type: Object,
    },
    // The security hash from ABA's callback, used to verify authenticity
    response_hash: {
        type: String,
    },
    // The final status message from ABA (e.g., 'approved', 'declined')
    gateway_status: {
        type: String,
    }
}, {
    timestamps: true,
});

abaSchema.index({transaction_id: 1});
abaSchema.index({external_reference: 1});

const Aba = mongoose.model('Aba', abaSchema);

module.exports = Aba;