const mongoose = require("mongoose");

const activityLogSchema = new mongoose.Schema(
  {
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
      index: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      index: true,
    },
    logType: {
      type: String,
      enum: ["ADMIN", "CUSTOMER", "USER"],
      required: true,
      index: true,
    },
    action: {
      type: String,
      required: true,
      enum: [
        "LOGIN",
        "LOGOUT",
        "REGISTER",
        "PASSWORD_RESET_REQUEST",
        "PASSWORD_RESET",
        "PROFILE_UPDATE",
        "USER_CREATE",
        "USER_UPDATE",
        "USER_DELETE",
        "USER_RESTORE",
        "USER_FORCE_DELETE",
        "USER_STATUS_UPDATE",
        "CUSTOMER_CREATE",
        "CUSTOMER_UPDATE",
        "CUSTOMER_DELETE",
        "CUSTOMER_RESTORE",
        "CUSTOMER_FORCE_DELETE",
        "ROLE_CREATE",
        "ROLE_DELETE",
        "PERMISSION_CREATE",
        "PERMISSION_DELETE",
        "MOVIE_CREATE",
        "MOVIE_UPDATE",
        "MOVIE_DELETE",
        "MOVIE_RESTORE",
        "MOVIE_FORCE_DELETE",
        "MOVIE_STATUS_UPDATE",
        "THEATER_CREATE",
        "THEATER_UPDATE",
        "THEATER_DELETE",
        "THEATER_RESTORE",
        "THEATER_FORCE_DELETE",
        "HALL_CREATE",
        "HALL_UPDATE",
        "HALL_DELETE",
        "HALL_RESTORE",
        "HALL_FORCE_DELETE",
        "SHOWTIME_CREATE",
        "SHOWTIME_UPDATE",
        "SHOWTIME_DELETE",
        "SHOWTIME_RESTORE",
        "SHOWTIME_FORCE_DELETE",
        "SHOWTIME_STATUS_UPDATE",
        "SEAT_CREATE",
        "SEAT_UPDATE",
        "SEAT_DELETE",
        "SEAT_RESTORE",
        "SEAT_FORCE_DELETE",
        "SEAT_BOOKING_UPDATE",
        "BOOK_CREATE_PENDING",
        "BOOK_CREATE_CONFIRMED",
        "BOOK_UPDATE",
        "BOOK_UPDATE_SEATS",
        "BOOK_CONFIRMED",
        "BOOK_CANCEL",
        "BOOK_CANCEL_PENDING",
        "BOOK_CANCEL_CONFIRMED",
        "BOOK_RESTORE",
        "BOOK_DELETE",
        "BOOK_FORCE_DELETE",
        "BOOK_EXPIRED",
        "PROMOTION_CREATE",
        "PROMOTION_UPDATE",
        "PROMOTION_DELETE",
        "PROMOTION_RESTORE",
        "PROMOTION_FORCE_DELETE",
        "PROMOTION_STATUS_UPDATE",
        "PAYMENT_CREATE",
        "PAYMENT_UPDATE",
        "PAYMENT_DELETE",
        "PAYMENT_STATUS_UPDATE",
        "PAYMENT_VERIFIED",
        "INVOICE_GENERATE",
        "INVOICE_DELETE",
        "NOTIFICATION_CREATE",
        "NOTIFICATION_UPDATE",
        "NOTIFICATION_DELETE",
        "NOTIFICATION_SEND",
        "REPORT_GENERATE",
        "FILE_UPLOAD",
        "FILE_DELETE",
        "ROLE_UPDATE",
        "PERMISSION_UPDATE",
      ],
      index: true,
    },
    status: {
      type: String,
      enum: ["SUCCESS", "FAILED"],
      default: "SUCCESS",
    },
    targetId: {
      type: mongoose.Schema.Types.ObjectId,
      index: true,
    }, // Reference to Booking, Showtime, etc.
    ipAddress: {
      type: String,
    },
    userAgent: {
      type: String,
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: { createdAt: true, updatedAt: false },
  },
);

// Indexes for performance
activityLogSchema.index({ customerId: 1, action: 1, createdAt: -1 });
activityLogSchema.index({ userId: 1, action: 1, createdAt: -1 });
activityLogSchema.index(
  { createdAt: 1 },
  { expireAfterSeconds: 60 * 60 * 24 * 90 },
); // Keep logs for 90 days

module.exports = mongoose.model("ActivityLog", activityLogSchema);
